nodes:
  - filepath: nodes.h5
    populations:
      - name: nodeA
        type: biophysical
        size: 2
        morphologies_asc: CircuitA/morphologies/asc
        morphologies_swc: CircuitA/morphologies/swc
        biophysical_neuron_models_dir: CircuitA/hoc

edges:
  - filepath: edges.h5
    populations:
      - source: nodeA
        target: nodeA
        type: chemical
        size: 4

simulations:
  globals:
    output_dir: "reporting"
    tstart: 0
    tstop: 1.0
    dt: 0.1
    spikes_file: "spikes.h5"
    spikes_sort_order: "time"
    spikes_count: 5

  reports:
    - name: "soma_report"
      cells: "node_set1"
      variable_name: "current_soma"
      sections: "soma"
    - name: "compartment_report"
      cells: "node_set2"
      variable_name: "current_compart"
      sections: "all"
