biophysical:
    x:
        type: float
        values: [-1000.0, 1000]
    y:
        type: float
        values: [-1000.0, 1000]
    z:
        type: float
        values: [-1000.0, 1000]
    orientation_w:
        type: float
        values: [-1.0, 1.0]
    orientation_x:
        type: float
        values: [-1.0, 1.0]
    orientation_y:
        type: float
        values: [-1.0, 1.0]
    orientation_z:
        type: float
        values: [-1.0, 1.0]
    morphology:
      type: text
      values: morphology
    model_template:
      type: text
      values: emodel
    layer:
        type: text
        values: [ 'LA', 'LB', 'LC']
    model_type:
        type: enum
        values: ['biophysical']
    morph_class:
        type: enum
        values: ["PYR", "INT"]
    etype:
        type: enum
        values: ["dNAC", "dSTUT"]
    mtype:
        type: enum
        values: ['L5_PC', 'L4_PC', 'L4_MC']
    synapse_class:
        type: enum
        values: ["EXC", "INH"]
    region:
        type: enum
        values: ['RA', 'RB']
    dynamics_params/threshold_current:
        type: float
        values: [1.0, 2.0]
    dynamics_params/holding_current:
        type: float
        values: [1.0, 2.0]
    dynamics_params/AIS_scaler:
        type: float
        values: [1.0, 2.0]
    minis:
        type: float
        values: [0, 100]
    hemisphere:
        type: enum
        values: ['left', 'right']

virtual:
    model_type:
        type: enum
        values: ['virtual']

