nodes:
  - filepath: nodes_A.h5
    populations:
      - name: NodeA
        type: biophysical
        size: 3
        morphologies_asc: CircuitA/morphologies/asc
        morphologies_swc: CircuitA/morphologies/swc
        biophysical_neuron_models_dir: CircuitA/hoc

  - filepath: virtual_nodes_A.h5
    populations:
      - name: VirtualPopA
        type: virtual
        size: 2

  - filepath: nodes_B.h5
    populations:
      - name: NodeB
        type: biophysical
        size: 2
        morphologies_asc: CircuitB/morphologies/asc
        morphologies_swc: CircuitB/morphologies/swc
        biophysical_neuron_models_dir: CircuitB/hoc
  - filepath: virtual_nodes_B.h5
    populations:
      - name: VirtualPopB
        type: virtual
        size: 2

edges:
  - filepath: local_edges_A.h5
    populations:
      - source: NodeA
        target: NodeA
        type: chemical
        size: 4
  - filepath: local_edges_B.h5
    populations:
      - source: NodeB
        target: NodeB
        type: chemical
        size: 4
  - filepath: edges_AB.h5
    populations:
      - source: NodeA
        target: NodeB
        type: chemical
        size: 4
      - source: NodeB
        target: NodeA
        type: chemical
        size: 4
  - filepath: projections_A.h5
    populations:
      - source: VirtualPopA
        target: NodeA
        type: chemical
        size: 4
  - filepath: projections_B.h5
    populations:
      - source: VirtualPopB
        target: NodeB
        type: chemical
        size: 4


