nodes:
  - filepath: nodes_A.h5
    populations:
      - name: NodeA
        type: biophysical
        size: 3
        morphologies_asc: CircuitA/morphologies/asc
        morphologies_swc: CircuitA/morphologies/swc
        biophysical_neuron_models_dir: CircuitA/hoc

  - filepath: virtual_nodes_A.h5
    populations:
      - name: VirtualPopA
        type: virtual
        size: 2

  - filepath: nodes_B.h5
    populations:
      - name: NodeB
        type: biophysical
        size: 2
        morphologies_asc: CircuitB/morphologies/asc
        morphologies_swc: CircuitB/morphologies/swc
        biophysical_neuron_models_dir: CircuitB/hoc
  - filepath: virtual_nodes_B.h5
    populations:
      - name: VirtualPopB
        type: virtual
        size: 2

edges:
  - filepath: local_edges_A.h5
    populations:
      - source: NodeA
        target: NodeA
        type: chemical
        size: 4
  - filepath: local_edges_B.h5
    populations:
      - source: NodeB
        target: NodeB
        type: chemical
        size: 4
  - filepath: edges_AB.h5
    populations:
      - source: NodeA
        target: NodeB
        type: chemical
        size: 4
      - source: NodeB
        target: NodeA
        type: chemical
        size: 4
  - filepath: projections_A.h5
    populations:
      - source: VirtualPopA
        target: NodeA
        type: chemical
        size: 4
  - filepath: projections_B.h5
    populations:
      - source: VirtualPopB
        target: NodeB
        type: chemical
        size: 4


simulations:
  globals:
    output_dir: "reporting"
    tstart: 0
    tstop: 1.0
    dt: 0.1
    spikes_file: "spikes.h5"
    spikes_sort_order: "by_time"
    spikes_count: 5
    random_seed: 0

  reports:
    - name: "soma_report"
      cells: "node_set1"
      variable_name: "v"
      sections: "soma"
      type: "compartment"
    - name: "compartment_report"
      cells: "node_set2"
      variable_name: "v"
      sections: "all"
      type: "compartment"
