nodes:
  - filepath: nodes.h5
    populations:
      - name: NodeA
        type: biophysical
        size: 2
        morphologies_asc: CircuitA/morphologies/asc
        morphologies_swc: CircuitA/morphologies/swc
        biophysical_neuron_models_dir: CircuitA/hoc
      - name: VirtualPopA
        type: virtual
        size: 2

edges:
  - filepath: edges.h5
    populations:
      - source: NodeA
        target: NodeA
        type: chemical
        size: 4
  - filepath: projections.h5
    populations:
      - source: VirtualPopA
        target: NodeA
        type: chemical
        size: 4


